### ISSUE TITLE
DNS Timeout exception is not catched

### ISSUE THREAD

**Issue by hajdbo** [jgamblin/isthisipbad#7]
```
Traceback (most recent call last):
  File "isthisipbad.py", line 211, in <module>
    answers = my_resolver.query(query, "A")
  File "/usr/lib/python2.7/dist-packages/dns/resolver.py", line 819, in query
    timeout = self._compute_timeout(start)
  File "/usr/lib/python2.7/dist-packages/dns/resolver.py", line 734, in _compute_timeout
    raise Timeout
dns.exception.Timeout
```

**Comment by hajdbo** [comment]
fixed with https://github.com/jgamblin/isthisipbad/commit/63f54875ab9b6253432a8f5fdfdb3b7a82a7b512

**Comment by jgamblin** [comment]
@hajdbo Thanks for fixing on it! : )
